[tox]
min_version = 4.0
env_list =
    py311
    py312
    py313
    py314

[testenv]
deps =
    .[test]
commands =
    pylint dappertable/
    bandit -r dappertable/
    pytest --cov=dappertable/ --cov-report=html --cov-fail-under=100 tests/

[pytest]
filterwarnings = error